spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/r_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver       # /r_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.imooc.pan
  title: r-pan-server docs
  description: r-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: rubin
  contact-url: https://blog.rubinchu.com
  contact-email: rubinchu@126.com
  version: 1.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO

com:
  imooc:
    pan:
      storage:
        engine:
          oss:
            bucket-name: web-tlias-zhs
            endpoint: oss-cn-chengdu.aliyuncs.com
            access-key-id: LTAI5tQPkLiKT5ZFS3rv48yj
            access-key-secret: zmR6f0Z9ms1xJYvHDumAxce8ubfwo0
            auto-create-bucket: true
#          fdfs:
#            connect-timeout: 600
#            tracker-list:
#              - 39.98.37.93:22122
#            group: group1
